TAB_ARGS = [
    {'order': 1, 'name': '일반 현황', 'value': 'tab_general_status', 'sub_tabs': [
        {'order': 1, 'name': '대학 기본정보', 'value': 'sub_tab_general_status_basic_info'},
        {'order': 2, 'name': '설립 및 운영주체', 'value': 'sub_tab_general_status_establishment_operation'},
        {'order': 3, 'name': '건학이념, 사명(미션),  비전', 'value': 'sub_tab_general_status_ideology_mission_vision'},
        {'order': 4, 'name': '교육목적, 교육목표', 'value': 'sub_tab_general_status_education_objective'},
        {'order': 5, 'name': '졸업성과', 'value': 'sub_tab_general_status_graduation_outcome'},
        {'order': 6, 'name': '학(원)장 선임 및 절차', 'value': 'sub_tab_general_status_appointment_procedure'},
        {'order': 7, 'name': '학(원)장의 인사권', 'value': 'sub_tab_general_status_appointment_power'},
        {'order': 8, 'name': '학(원)장의 재정권', 'value': 'sub_tab_general_status_appointment_finance_power'},
        {'order': 9, 'name': '행정 구조', 'value': 'sub_tab_general_status_administrative_structure'},
        {'order': 10, 'name': '기구도', 'value': 'sub_tab_general_status_organization'},
    ]},
    {'order': 2, 'name': '교육 과정', 'value': 'tab_education_process', 'sub_tabs': [
        {'order': 1, 'name': '교육과정위원회', 'value': 'sub_tab_education_process_curriculum_committee'},
        {'order': 2, 'name': '교육과정 특성', 'value': 'sub_tab_education_process_curriculum_characteristics'},
        {'order': 3, 'name': '개설 교과목', 'value': 'sub_tab_education_process_curriculum_subject'},
        {'order': 4, 'name': '임상실습', 'value': 'sub_tab_education_process_curriculum_clinical_practice'},
        {'order': 5, 'name': '진료수행, 임상술기 교육시간', 'value': 'sub_tab_education_process_curriculum_clinical_practice_time'},
        {'order': 6, 'name': '학생 평가', 'value': 'sub_tab_education_process_student_evaluation'},
        {'order': 7, 'name': '의학교육 전문부서 및 인력', 'value': 'sub_tab_education_process_educational_department'},
        {'order': 8, 'name': '의료인문학 전문부서 및 인력', 'value': 'sub_tab_education_process_medical_humanities'},
    ]},
    {'order': 3, 'name': '학생', 'value': 'tab_student', 'sub_tabs': [
        {'order': 1, 'name': '입학 제도', 'value': 'sub_tab_student_admission_system'},
        {'order': 2, 'name': '입학 학생수', 'value': 'sub_tab_student_admission_student'},
        {'order': 3, 'name': '재적 학생수', 'value': 'sub_tab_student_enrolled_student'},
        {'order': 4, 'name': '의예과 입학 학생 구성', 'value': 'sub_tab_student_admission_student_structure'},
        {'order': 5, 'name': '장학금 수혜 현황', 'value': 'sub_tab_student_scholarship'},
        {'order': 6, 'name': '졸업생의 진로', 'value': 'sub_tab_student_graduate_career'},
        {'order': 7, 'name': '의학계열 대학원 학생 수 ', 'value': 'sub_tab_student_graduate_student'},
        {'order': 8, 'name': '교육병원', 'value': 'sub_tab_student_education_hospital'},
        {'order': 9, 'name': '학생지원 전담기구', 'value': 'sub_tab_student_student_support'},
        {'order': 10, 'name': '주요 학생지원 프로그램', 'value': 'sub_tab_student_student_support_program'},
        {'order': 11, 'name': '학생 건강검진', 'value': 'sub_tab_student_student_health_checkup'},
        {'order': 12, 'name': '학생 안전관리', 'value': 'sub_tab_student_student_safety_management'},
        {'order': 13, 'name': '지도교수 1인당 평균 학생수', 'value': 'sub_tab_student_student_per_professor'},
        {'order': 14, 'name': '학생 국제교류 현황', 'value': 'sub_tab_student_student_international_exchange'},
    ]},
    {'order': 4, 'name': '교수', 'value': 'tab_professor', 'sub_tabs': [
        {'order': 1, 'name': '교원 수', 'value': 'sub_tab_professor_professor'},
        {'order': 2, 'name': '전임교원 수 변화', 'value': 'sub_tab_professor_full_time_professor'},
        {'order': 3, 'name': '의학교육 관련 연수', 'value': 'sub_tab_professor_medical_education_training'},
        {'order': 4, 'name': '교수개발과 승진 체계', 'value': 'sub_tab_professor_professor_development_promotion_system'},
    ]},
    {'order': 5, 'name': '시설', 'value': 'tab_facility', 'sub_tabs': [
        {'order': 1, 'name': '교육기본시설', 'value': 'sub_tab_facility_education_basic_facility'},
        {'order': 2, 'name': '의학도서관', 'value': 'sub_tab_facility_medical_library'},
        {'order': 3, 'name': '학생 소그룹 토의실', 'value': 'sub_tab_facility_student_small_group_discussion_room'},
        {'order': 4, 'name': '기숙사', 'value': 'sub_tab_facility_dormitory'},
        {'order': 5, 'name': '학생 자율학습 공간', 'value': 'sub_tab_facility_student_self_study_space'},
        {'order': 6, 'name': '학생 복지시설 및 편의시설', 'value': 'sub_tab_facility_student_welfare_facility'},
        {'order': 7, 'name': '교육정보화 시스템', 'value': 'sub_tab_facility_education_information_system'},
        {'order': 8, 'name': '학생 연구실험실', 'value': 'sub_tab_facility_student_research_laboratory'},
    ]},
    {'order': 6, 'name': '경영, 재정', 'value': 'tab_management_finance', 'sub_tabs': [
        {'order': 1, 'name': '교수 역량개발 관련 비용', 'value': 'sub_tab_management_finance_professor_development'},
        {'order': 2, 'name': '학생교육 관련 비용', 'value': 'sub_tab_management_finance_student_education'},
        {'order': 3, 'name': '학생 등록금 (1인당)', 'value': 'sub_tab_management_finance_student_tuition'},
    ]},
    {'order': 7, 'name': 'DB 추출', 'value': 'tab_notice_db_extraction', 'sub_tabs': [
        {'order': 1, 'name': 'DB 추출', 'value': 'sub_tab_notice_db_extraction'},
    ]}
]
